### PR TITLE
Sprint 4 Team Voldemort Integrated

### PR DESCRIPTION
**Pull request by DWallis94**
Please review 'coinmart.db.better' to replace the current db file 'coinmart.db' (simply delete and rename to overwrite). The existing coinmart.db file contains many incompatibilities with all teams' code

### CODE REVIEW

**Comment by whwong-sit** [comment]
is schema.sql consistent with coinmart.db.better?

**Comment by DWallis94** [comment]
One small discrepancy. Fixed in this one

**Comment by whwong-sit** [comment]
is this PR compatible with Hema's?

**Comment by DWallis94** [comment]
It's compatible with the current head, however I don't know whether Hema's code is compatible with the current head.
________________________________

**Pull request merged**
